services:
  - type: web
    name: innovasoft-api
    region: oregon
    pythonVersion: "3.12"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        fromGroup: innovasoft-secrets
      - key: DB_NAME
        value: innovasofpythonpruebatecnica
      - key: INNOVASOFT_URL
        value: https://pruebareactjs.test-class.com/Api